// Generated from: /home/usuario/dev/icaroglauco.online/src/main.dsljs
// Do not edit this file directly.

import { createPortfolioStructuralKit } from "./dsl/app-construct.generated.ts";

const portfolioStructuralKit = createPortfolioStructuralKit();

export const renderAppShell = portfolioStructuralKit.renderers.renderAppShell;
export const createApplicationShellComponent = portfolioStructuralKit.structuralComponents.createApplicationShellComponent;

export const portfolioApplication = function () {
      const appName = "Icaro Glauco Portfolio";
      const layouts = { overview: "identity-editorial",
    portfolio: "technical-pager",
    agent: "contact-intake",
    "ai-engineering": "technical-pager",
    "systems-explorer": "technical-pager",
    engineering: "technical-pager",
    experience: "technical-pager",
    interactive: "technical-pager",
    contact: "technical-pager" };
      const assistant = { name: "icaroIA",
    kicker: "agente de orientação comercial",
    tooltip:
      "Carrego a intenção profissional, a leitura estrutural e o repertório comercial do meu autor para orientar conversas, esclarecer contexto e preparar relatórios ou pré-propostas iniciais." };

      return {
        name: () => appName,
        layouts: () => layouts,
        assistant: () => assistant,
        version: "0.6.0",
        mode: "macro-tree-structural",
        contentSource: "markdown-public",
        contentPath: "/content/sections",
        entry: "main.dsljs",
        structureModel: "element-tree-to-app-concepts",
      };
    };


globalThis.__PORTFOLIO_APPLICATION__ = portfolioApplication();
globalThis.__PORTFOLIO_ELEMENTS__ = portfolioStructuralKit.elements;
globalThis.__PORTFOLIO_CONCEPTS__ = portfolioStructuralKit.concepts;
globalThis.__PORTFOLIO_SCENE_SEMANTICS__ = portfolioStructuralKit.sceneSemantics;
globalThis.__PORTFOLIO_STRUCTURAL_COMPONENTS__ = portfolioStructuralKit.structuralComponents;
globalThis.__PORTFOLIO_COMPONENTS__ = portfolioStructuralKit.renderers;
globalThis.__PORTFOLIO_RENDERERS__ = portfolioStructuralKit.renderers;
globalThis.__PORTFOLIO_SLIDES__ = portfolioStructuralKit.slideBuilders;

await import("/src/runtime/app-runtime.generated.ts");
