// Generated from: /home/usuario/dev/icaroglauco.online/src/screens.dsljs
// Do not edit this file directly.
export type ScreenBullet = string;

export type ScreenDeepDive = {
  kicker: string;
  title: string;
  body: string;
  list?: string[];
};

export type IdentityDeckEntry = {
  src: string;
  alt: string;
  caption: string;
};

export type IdentityMilestone = {
  year: string;
  title: string;
  body: string;
};

export type ScreenSlide = {
  title: string;
  body: string;
  label?: string;
  intro?: string;
  support?: string;
  chips?: string[];
  list?: string[];
};

export type ScreenView = {
  distance: number;
  side: number;
  height: number;
  lookHeight: number;
  lookSide: number;
  fov: number;
};

export type PortfolioScreen = {
  id: string;
  code: string;
  label: string;
  kicker: string;
  headline: string;
  blurb: string;
  details: string;
  bullets: ScreenBullet[];
  contentTitle: string;
  contentBody: string;
  contentNotes?: string[];
  deepDives?: ScreenDeepDive[];
  kind?: string;
  image?: string;
  backgroundImage?: string;
  backgroundPosition?: string;
  portraitImage?: string;
  portraitCaption?: string;
  identityLead?: string;
  identityHighlights?: string[];
  identityMilestones?: IdentityMilestone[];
  identityDeck?: IdentityDeckEntry[];
  identityPagerTitle?: string;
  identityPagerIntro?: string;
  identityPagerSlides?: ScreenSlide[];
  profilePath?: string;
  profileLinkLabel?: string;
  agentEndpoint?: string;
  agentStrategy?: string;
  agentMode?: string;
  profileSummary?: string;
  profileHighlights?: string[];
  quickPrompts?: string[];
  agentGreeting?: string;
  agentPanelCopy?: string;
  agentFormLabel?: string;
  agentPlaceholder?: string;
  reportTitle?: string;
  reportHeading?: string;
  reportFilename?: string;
  reportNotice?: string;
  view: ScreenView;
};

export const screens: PortfolioScreen[] = [
  {
    id: "overview",
    code: "01 / FUNDAMENTO",
    label: "Identidade",
    kicker: "Base profissional",
    headline: "Design, frontend e leitura de produto apoiados por uma base técnica rara e consistente",
    blurb:
      "Esta abertura apresenta a origem do meu trabalho: anos de formação técnica, repertório visual e prática em interface convertidos em critério de produto, decisão e entrega.",
    details:
      "Meu perfil foi sendo construído na continuidade entre eletrônica, webdesign, computação gráfica, programação e frontend. Hoje essa trajetória se traduz numa leitura que conecta linguagem visual, estrutura e é orientada à produto.",
    bullets: [
      "Base técnica anterior ao mercado",
      "Design e UX como filtros de decisão",
      "Frontend com leitura de produto e implementação"
    ],
    kind: "identity",
    contentTitle: "Por que essa base melhora a entrega",
    contentBody:
      "Quando entro num projeto, não olho apenas para a tela nem apenas para o código. Leio problema, interface, estrutura e narrativa de uso ao mesmo tempo. Essa base reduz improviso, qualifica a decisão e dá direção antes da execução ganhar volume.",
    contentNotes: [
      "Interface pensada junto com estrutura",
      "Decisão visual ligada à função real",
      "Mais clareza de produto antes da implementação"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / aplicação",
        title: "Como essa origem vira vantagem de entrega",
        body:
          "Na prática, essa origem me faz começar pelo que realmente organiza o projeto: o problema que precisa ser resolvido, a forma como ele aparece para a pessoa usuária e a arquitetura que sustenta a experiência. Em vez de empilhar telas, procuro dar borda, ritmo e coerência ao sistema desde cedo.",
        list: [
          "Leitura simultânea de problema, interface e implementação",
          "Traduzo intuição visual em decisão concreta",
          "Procuro coerência entre UX, linguagem e entrega"
        ]
      },
      {
        kicker: "Camada 2 / evidencias",
        title: "Evidências concretas dessa trajetória",
        body:
          "Essa trajetória aparece em marcos objetivos: primeiro trabalho web ainda no ensino médio, aprofundamento em CSS3 em 2014, base formal em Ciência da Computação a partir de 2015, aplicativo comercial em 2018 e consolidação profissional em frontend nos anos seguintes.",
        list: [
          "Webdesign e autoria visual antes do mercado",
          "Fundamento técnico convivendo com sensibilidade de interface",
          "Passagem consistente de curiosidade para ofício"
        ]
      }
    ],
    portraitImage: "/assets/foto-02.jpg",
    portraitCaption: "Retrato editorial / base profissional",
    identityLead:
      "Minha entrada na área não nasceu de uma tendência de mercado. Nasceu de uma formação técnica e visual que hoje me permite estruturar interfaces, produtos e experiências com mais clareza, critério e consistência.",
    identityHighlights: [
      "Técnico em Informática como base de formação",
      "Estudos de eletrônica e lógica desde cedo",
      "Webdesign e computação gráfica antes da atuação profissional",
      "CSS3 como eixo de linguagem visual desde 2014",
      "Ciência da Computação ampliando repertório estrutural",
      "Aplicativos Android com mapas, SVG e Firebase em 2018",
      "Frontend profissional a partir de 2022",
      "IA integrada ao processo de estudo e desenvolvimento em 2024"
    ],
    identityMilestones: [
      {
        year: "09 anos",
        title: "Portas logicas, LED e curiosidade antes da faculdade",
        body:
          "Meu primeiro fascínio técnico veio cedo: livros de eletrônica, componentes básicos, portas lógicas e circuitos simples enquanto eu acompanhava meu pai na UESB."
      },
      {
        year: "2013",
        title: "Primeiro trabalho web ainda no ensino médio",
        body:
          "Depois de mais de dois anos estudando design web, fiz meu primeiro trabalho de implementação de website num momento em que CSS3 e computação gráfica ampliavam a sensação de interatividade na web."
      },
      {
        year: "2014",
        title: "CSS3 e WordPress como escola de linguagem visual",
        body:
          "No fim de 2014 eu me aprofundei em CSS3 e montei uma página em WordPress com transições animadas e efeitos sonoros por sessão. Foi um exercício direto de atmosfera, interação e narrativa visual."
      },
      {
        year: "2015",
        title: "Ciência da Computação e gosto por estrutura",
        body:
          "Entrei em Ciência da Computação e ampliei repertório em programação, linguagens formais, autômatos, lógica e tipagem. Isso reforçou o lado estrutural que hoje sustenta minha leitura de interface."
      },
      {
        year: "2022-2024",
        title: "Frontend como oficio e IA como amplificador",
        body:
          "Em 2022 comecei a viver de frontend. Em 2024 a IA entrou no processo como ferramenta diária de estudo, iteração e desenvolvimento, sem substituir critério nem responsabilidade."
      }
    ],
    identityDeck: [
      {
        src: "/identity/doce-flauta.png",
        alt: "Projeto artistico A Doce Flauta da Liberdade",
        caption: "2013 / A Doce Flauta da Liberdade"
      },
      {
        src: "/identity/caminho-parque.png",
        alt: "Banner do loteamento Caminho do Parque",
        caption: "2018 / Caminho do Parque"
      },
      {
        src: "/identity/app-caminho-parque.png",
        alt: "Screenshots do aplicativo Caminho do Parque",
        caption: "2018 / App de vendas em Android"
      }
    ],
    identityPagerTitle: "2017-2018 / produto comercial e leitura de mapas",
    identityPagerIntro:
      "No ciclo do app imobiliário, eu vi técnica, operação e usabilidade se encontrarem com clareza. Estes recortes mostram onde isso virou valor concreto.",
    identityPagerSlides: [
      {
        title: "Ideia ligada a uma dor real",
        body:
          "Na metade de 2017 apresentei uma ideia para um corretor que trabalhava com meu pai. A proposta atacava uma dor concreta: reduzir deslocamentos entre campo e escritório e substituir mapas imprecisos por uma leitura comercial mais útil do loteamento."
      },
      {
        title: "Aplicativo, mapa e stack",
        body:
          "Em 2018 eu desenvolvia aplicativos Android para apoiar comunicação de vendas. Nesse caso trabalhei com manipulação de SVG, pinch zoom, scroll views e Firebase Realtime Database para sustentar a leitura do mapa no momento da operação."
      },
      {
        title: "Validacao em uso",
        body:
          "O auge veio no final de 2018, em Amargosa. Houve elogios pela iniciativa e pela utilidade do aplicativo no processo comercial. Foi um caso claro de tecnologia entrando no ponto exato da decisão e qualificando a conversa com o cliente."
      }
    ],
    image: "/assets/foto-01.jpg",
    backgroundImage: "/assets/foto-06.jpg",
    backgroundPosition: "center 52%",
    view: {
      distance: 4.8,
      side: -0.45,
      height: 1.25,
      lookHeight: 1.18,
      lookSide: -0.12,
      fov: 30
    }
  },
  {
    id: "portfolio",
    code: "02 / REQUISITOS",
    label: "Requisitos",
    kicker: "Leitura de problema",
    headline: "Requisitos bem conduzidos transformam demanda difusa em direção clara de produto",
    blurb:
      "É aqui que eu tiro o projeto do campo da intuição vaga e dou forma útil a ele: contexto, atores, entidades, fluxo, restrições e critério de decisão.",
    details:
      "Eu uso IA para acelerar descoberta e síntese, não para substituir leitura. O valor desta etapa está em transformar ruído em estrutura e estrutura em escolhas que sirvam ao negócio, à interface e à operação.",
    bullets: [
      "Entrevista e leitura antes da implementação",
      "Contexto traduzido em entidade, fluxo e regra",
      "IA como acelerador de síntese, não como atalho vazio"
    ],
    contentTitle: "Como eu organizo requisitos",
    contentBody:
      "Não espero um briefing perfeito para começar bem. Procuro esclarecer onde o pedido ainda está confuso, qual dor é real, o que precisa virar regra ou fluxo e onde existe oportunidade escondida. Isso reduz desperdício, acelera alinhamento e melhora a qualidade da decisão.",
    contentNotes: [
      "Sintoma separado de necessidade estrutural",
      "Linguagem do cliente traduzida em modelo de trabalho",
      "Negócio, interface e arquitetura lidos em conjunto"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / resultado",
        title: "O que uma boa leitura de requisitos destrava",
        body:
          "Quando essa etapa é bem conduzida, o projeto ganha borda. Fica mais claro o que entra e o que não entra, quais dados importam, como a interface deve responder e onde existe ganho operacional ou comercial relevante.",
        list: [
          "Escopo com menos ambiguidade",
          "Interface mais aderente ao uso real",
          "Conversas futuras menos caras e menos confusas"
        ]
      },
      {
        kicker: "Camada 2 / aprofundamento",
        title: "Como eu aprofundo sem deixar a conversa vaga",
        body:
          "Costumo aprofundar em duas frentes: primeiro nomeio o que o sistema realmente é; depois testo o que ele precisa sustentar em cena de uso. Assim a conversa sai do discurso genérico e encosta em entrega, risco, valor e comportamento.",
        list: [
          "Perguntas que puxam contexto, ator, fluxo e restrição",
          "Leitura de negócio junto com leitura de interface",
          "IA entrando para acelerar síntese, não para inventar fundamento"
        ]
      }
    ],
    image: "/assets/foto-02.jpg",
    backgroundImage: "/ambient/sky-island.jpg",
    backgroundPosition: "center center",
    view: {
      distance: 5.15,
      side: 0.82,
      height: 1.5,
      lookHeight: 1.3,
      lookSide: 0.18,
      fov: 32
    }
  },
  {
    id: "agent",
    code: "03 / CONTATO",
    label: "Contato",
    kicker: "Intake guiado",
    headline: "Conversa guiada para transformar interesse em escopo, encaixe e próxima etapa",
    blurb:
      "Eu uso esta etapa para tirar o contato do nível genérico e levar a conversa para objetivo, contexto, escopo e sinais concretos de encaixe.",
    details:
      "Eu mantenho a exportação em markdown bloqueada enquanto essas bases não aparecem. O objetivo aqui é evitar documento bonito apoiado em informação fraca ou premissa mal entendida.",
    bullets: [
      "Coleta guiada de objetivo, contexto e escopo",
      "Cláusulas provisórias de aplicabilidade",
      "Exportação liberada só com material suficiente"
    ],
    contentTitle: "Como a triagem mede encaixe e aplicabilidade real",
    contentBody:
      "Aqui eu organizo o que a pessoa quer construir, por que isso importa agora, o que já dá para recortar como entrega e em que medida meu perfil faz sentido para o caso.",
    contentNotes: [
      "Não exporta com contexto insuficiente",
      "Prioriza trabalhos com interface, requisitos, agentes e software autoral",
      "Entrega uma prévia de proposta, não um contrato fechado"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / base mínima",
        title: "Quatro blocos para liberar uma prévia forte",
        body:
          "Para eu liberar a prévia, a conversa precisa sair do interesse genérico e chegar a quatro zonas: objetivo do trabalho, contexto ou dor real, recorte inicial de escopo e algum sinal de por que meu perfil faz sentido para o caso.",
        list: [
          "O que você quer colocar de pé",
          "Qual problema, oportunidade ou operação está por trás",
          "Quais entregáveis entram de verdade",
          "Por que isso conversa com meu modo de trabalhar"
        ]
      },
      {
        kicker: "Camada 2 / condição da prévia",
        title: "O que a exportação entrega e o que ela ainda não promete",
        body:
          "Quando eu libero a exportação, ela gera um diagnóstico preliminar de interesse e aplicabilidade. Eu uso esse material para organizar a conversa, explicitar condições iniciais e apontar próximos passos, sem fingir que contrato e escopo final já estão fechados.",
        list: [
          "Resume interesse declarado e sinais de encaixe",
          "Lista cláusulas provisórias de aplicabilidade",
          "Mostra o que ainda precisa ser validado antes de um acordo"
        ]
      }
    ],
    kind: "agent",
    profilePath: "/llm/icaro-workstyle.md",
    profileLinkLabel: "Abrir base de trabalho (.md)",
    agentEndpoint: "/api/agent-chat",
    agentStrategy: "remote-ai",
    agentMode: "contact-intake",
    profileSummary:
      "Use esta conversa para sair do interesse difuso e chegar a um diagnóstico inicial de encaixe, limites e próximo passo de proposta.",
    profileHighlights: [
      "Objetivo e resultado esperado",
      "Contexto, dor real e sinais de negócio",
      "Escopo, restrições e por que meu perfil faz sentido"
    ],
    quickPrompts: [
      "Quero entender se meu projeto combina com seu perfil.",
      "Tenho uma necessidade em produto e interface e quero estruturar melhor o escopo.",
      "Quero sair desta conversa com uma prévia inicial de proposta."
    ],
    agentGreeting:
      "Descreva o que você quer construir, em que contexto isso aparece e por que meu perfil entrou nessa conversa. Quando houver base suficiente, eu libero uma prévia em markdown.",
    agentPanelCopy:
      "Eu uso esta conversa guiada para transformar interesse, contexto e escopo em uma prévia realista de proposta e aplicabilidade.",
    agentFormLabel: "Descreva seu interesse, contexto, escopo ou a próxima camada que devo aprofundar",
    agentPlaceholder:
      "Ex.: quero estruturar uma landing com camada editorial e intake guiado para um produto ainda difuso; preciso entender escopo, encaixe e próximos passos.",
    reportTitle: "Prévia de proposta",
    reportHeading: "Diagnóstico preliminar de interesse e aplicabilidade",
    reportFilename: "previa-proposta-icaro-glauco.md",
    reportNotice:
      "A exportação só libera quando a conversa trouxer base suficiente de objetivo, contexto, escopo e sinais de encaixe com meu perfil profissional.",
    image: "/assets/foto-07.jpg",
    backgroundImage: "/ambient/night-sentinel.jpg",
    backgroundPosition: "center center",
    view: {
      distance: 5.35,
      side: 1.36,
      height: 2.05,
      lookHeight: 1.54,
      lookSide: 0.28,
      fov: 28
    }
  },
  {
    id: "ai-engineering",
    code: "04 / IA APLICADA",
    label: "Agentes",
    kicker: "Método e governança",
    headline: "IA amplia capacidade quando entra com método, critério e responsabilidade",
    blurb:
      "Minha leitura de engenharia com IA é pragmática: agentes aceleram pesquisa, síntese e iteração, mas não substituem critério, curadoria nem responsabilidade de entrega.",
    details:
      "Para mim, o ganho real aparece quando existe processo. Sem processo, IA só aumenta a velocidade do erro com boa aparência. Com processo, ela amplia ambição, profundidade e ritmo de execução.",
    bullets: [
      "Acelera leitura, escrita e iteração",
      "Exige validação e refinamento contínuo",
      "Responsabilidade continua humana"
    ],
    contentTitle: "Como IA entra no meu processo",
    contentBody:
      "Uso agentes para explorar caminhos, organizar raciocínio, comparar opções e acelerar implementação. Mas a última palavra sobre qualidade, risco e adequação continua comigo.",
    contentNotes: [
      "Método antes de throughput",
      "Resposta pronta ainda precisa de leitura forte",
      "Polimento virou diferencial competitivo"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / operação",
        title: "Onde agentes realmente entram no fluxo de trabalho",
        body:
          "Eu coloco agentes para leitura de contexto, destravamento de implementação, comparação de caminhos, organização de requisitos e aceleração de refino. O ponto forte aqui não é pedir magia; é iterar com muito mais frequência mantendo intenção e controle.",
        list: [
          "Pesquisa e síntese com contexto suficiente",
          "Iteração mais rápida entre ideia, escrita e verificação",
          "Apoio forte em planejamento, arquitetura e acabamento"
        ]
      },
      {
        kicker: "Camada 2 / limite",
        title: "O que eu não terceirizo para nenhum modelo",
        body:
          "Não terceirizo julgamento final, assinatura de qualidade, leitura de risco nem responsabilidade pelo que vai ao ar. Se uma resposta parece limpa, mas está errada, continua errada, e isso precisa ser assumido por quem opera.",
        list: [
          "Não terceirizo critério",
          "Não trato velocidade como prova de qualidade",
          "Não confundo assistência com autoria completa"
        ]
      }
    ],
    image: "/assets/foto-05.jpg",
    backgroundImage: "/ambient/dawn-boat.jpg",
    backgroundPosition: "center center",
    view: {
      distance: 5.1,
      side: -1.08,
      height: 1.72,
      lookHeight: 1.44,
      lookSide: -0.22,
      fov: 29
    }
  },
  {
    id: "systems-explorer",
    code: "05 / LINGUAGEM",
    label: "Linguagens",
    kicker: "Pesquisa aplicada",
    headline: "Pesquisa de linguagem e tooling próprio para reduzir atrito entre ideia, interface e software",
    blurb:
      "Neste eixo, eu trato linguagem como mais do que sintaxe: para mim ela também é ergonomia, composição, runtime e autoria.",
    details:
      "Glauco Ruby e dsljs nasceram da mesma inquietação: investigar formas mais coesas de escrever, distribuir e operar software, especialmente em cenários autorais e de produto.",
    bullets: [
      "Pesquisa de linguagem aplicada a produto e tooling",
      "Glauco Ruby como experimento de runtime desktop solo",
      "dsljs como ferramenta própria orientada a macros"
    ],
    contentTitle: "O que eu busco com essa pesquisa",
    contentBody:
      "Meu lado de pesquisador aparece quando linguagem deixa de ser só API e vira ambiente de construção. O que me interessa é reduzir atrito entre semântica, implementação, interface e entrega, principalmente em cenários autorais ou solo.",
    contentNotes: [
      "Runtime local como campo de pesquisa",
      "Semântica aplicada à ergonomia de software",
      "Tooling próprio como laboratório útil, não fetiche"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / Glauco Ruby",
        title: "O que esse framework busca investigar",
        body:
          "Com Glauco Ruby, eu exploro uma ponte mais direta entre backend, frontend e app desktop local. O objetivo é estudar um caminho mais coeso para software solo, menos inchado e mais controlável do que stacks onde tudo já nasce fragmentado.",
        list: [
          "Menos atrito entre camadas",
          "Mais autoria sobre runtime e interface",
          "Pesquisa feita para servir produto futuro"
        ]
      },
      {
        kicker: "Camada 2 / dsljs",
        title: "Por que macros entram nessa linha de investigação",
        body:
          "Eu desenvolvi o dsljs para experimentar linguagem como mecanismo de composição e autoria. Em vez de aceitar JavaScript apenas como superfície de uso, eu testo como ele pode ser expandido para reduzir repetição e tornar certas formas de escrita mais expressivas.",
        list: [
          "Macro como ferramenta de composição",
          "Pesquisa ligada à ergonomia real de desenvolvimento",
          "IA ajudando a prototipar e tensionar possibilidades"
        ]
      }
    ],
    image: "/assets/foto-03.jpg",
    backgroundImage: "/ambient/sky-island.jpg",
    backgroundPosition: "center center",
    view: {
      distance: 4.7,
      side: -0.62,
      height: 2.28,
      lookHeight: 1.72,
      lookSide: -0.04,
      fov: 27
    }
  },
  {
    id: "engineering",
    code: "06 / ENGENHARIA",
    label: "Engenharia",
    kicker: "Base técnica",
    headline: "Arquitetura técnica para sustentar experiência, clareza de código e evolução de produto",
    blurb:
      "Eu trato a pilha técnica como infraestrutura de comportamento: cena, navegação, componentes, estado e publicação trabalhando em conjunto.",
    details:
      "Não me interessa stack como vitrine. Me interessa uma base capaz de sustentar assinatura visual, legibilidade de implementação e evolução real sem desmontar o projeto a cada iteração.",
    bullets: [
      "Three.js como espaço estrutural",
      "Vite para iteração rápida",
      "Firebase como camada pragmática de publicação"
    ],
    contentTitle: "Como eu penso a base técnica",
    contentBody:
      "Vite, three.js e Firebase entram aqui como base operacional. O objetivo é sustentar uma linguagem visual densa sem perder clareza de implementação nem capacidade de evolução. A escolha técnica precisa servir comportamento, não apenas caber no currículo.",
    contentNotes: [
      "Stack orientada a comportamento",
      "Cena 3D como sistema, não enfeite",
      "Infra pensada para crescer sem colapsar"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / comportamento",
        title: "O que a técnica precisa sustentar de verdade",
        body:
          "Eu preciso que a técnica sustente foco, navegação, continuidade espacial, modularidade e performance suficiente para que a experiência não pareça colagem de partes isoladas. Quero que o sistema se comporte como um corpo único.",
        list: [
          "Movimento coerente entre menu, cena e conteúdo",
          "Componentes legíveis para iterar sem medo",
          "Base pronta para receber novas camadas"
        ]
      },
      {
        kicker: "Camada 2 / manutenção",
        title: "O que impede a arquitetura de virar peso morto",
        body:
          "Tento manter o código perto da intenção. Quando comportamento, estado e visual ficam compreensíveis, o projeto continua vivo. Quando tudo vira gambiarra invisível, qualquer evolução futura fica cara demais.",
        list: [
          "Separação clara entre dados, renderização e cena",
          "Escolhas simples onde o problema pede simplicidade",
          "Espaço para evolução sem refazer o projeto inteiro"
        ]
      }
    ],
    image: "/assets/foto-04.jpg",
    backgroundImage: "/assets/foto-05.jpg",
    backgroundPosition: "center 28%",
    view: {
      distance: 5.5,
      side: 1.18,
      height: 1.08,
      lookHeight: 1.28,
      lookSide: 0.05,
      fov: 30
    }
  },
  {
    id: "experience",
    code: "07 / EXPERIENCIAS",
    label: "Experiencias",
    kicker: "Mundo, operacao e pessoas",
    headline: "Vivencias pessoais que ampliaram minha leitura de mundo, responsabilidade pratica e maturidade de trabalho",
    blurb:
      "Esta secao reune experiencias fora do eixo estrito de design e frontend, mas decisivas para meu modo de ler pessoas, operacao, cultura e responsabilidade concreta.",
    details:
      "Viagem internacional, administracao de pessoal em construcao rural e rotina de escritorio imobiliario me deram uma base menos teorica e mais viva sobre organizacao, conduta, prioridade, confianca e coordenacao no mundo real.",
    bullets: [
      "Irlanda como ampliacao de mundo e referencia civilizatoria",
      "Construcao rural com lideranca, compras e encarregamento geral",
      "Escritorio imobiliario como leitura administrativa e comercial"
    ],
    contentTitle: "O que essas vivencias acrescentam ao meu trabalho",
    contentBody:
      "Essas experiencias me ajudaram a ler trabalho para alem da interface. Vi de perto como cultura, organizacao, disciplina, diversidade, responsabilidade e ritmo operacional moldam ambientes, pessoas e resultados. Hoje isso volta para o meu trabalho como mais criterio, mais maturidade e mais nocao de realidade.",
    contentNotes: [
      "Leitura de mundo para alem da bolha tecnica",
      "Experiencia real com coordenacao, responsabilidade e ritmo",
      "Mais sensibilidade para cultura, estrutura e convivio humano"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / Irlanda",
        title: "Oito meses de Irlanda como expansao de mundo e de perspectiva sobre vida e trabalho",
        body:
          "A passagem pela Irlanda ampliou minha visao sobre pessoas, convivio, trabalho e sociedade. Foi um contato direto com um lugar de heranca antiga, atualidade informatica e abertura cultural, onde diversidade, imigrantes e tribos urbanas coexistem com regras formais, infraestrutura confiavel e valores humanos praticados no cotidiano. Essa vivencia me fez observar com mais clareza as constantes que ajudam lugares a crescerem como primeiro mundo: respeito ao tempo, ao espaco comum, ao acordo formal, ao trabalho bem feito e a uma organizacao coletiva que nao depende apenas de improviso.",
        list: [
          "Ampliacao de perspectiva sobre cultura, convivencia e trabalho",
          "Observacao pratica de valores humanos e formais funcionando juntos",
          "Contato com diversidade real, imigracao e ambiente aberto sem perder estrutura"
        ]
      },
      {
        kicker: "Camada 2 / construcao rural",
        title: "Responsabilidade de guiar frentes de trabalho em construcao e organizacao rural",
        body:
          "Na construcao rural, atuei com guiacao, responsabilidade e orientacao de grupos de trabalhadores em uma operacao que envolvia estrutura de condominio, construcao de casas, maquinas pesadas, compra de material e encarregamento geral. Essa experiencia me colocou numa posicao de coordenar pessoas, cobrar andamento, decidir prioridade, resolver entrave de obra e manter a operacao avancando com mais ordem e responsabilidade.",
        list: [
          "Orientacao de equipes de trabalho em campo",
          "Leitura de prioridade entre obra, material, maquina e prazo",
          "Encarregamento geral com foco em andamento e responsabilidade"
        ]
      },
      {
        kicker: "Camada 3 / escritorio imobiliario",
        title: "Escritorio imobiliario como leitura administrativa, comercial e de relacionamento",
        body:
          "A experiencia em escritorio imobiliario reforcou minha leitura de rotina administrativa, articulacao entre campo e escritorio, acompanhamento de demandas, conversa com pessoas e organizacao pratica do trabalho. Esse tipo de ambiente mostra como informacao, confianca, documento, ritmo e atendimento se conectam na operacao diaria, e me ajudou a amadurecer a forma como leio responsabilidade e comunicacao.",
        list: [
          "Mais leitura administrativa e comercial do cotidiano",
          "Contato com fluxo real entre operacao, escritorio e pessoas",
          "Maturidade de comunicacao, organizacao e confiabilidade"
        ]
      }
    ],
    image: "/assets/foto-07.jpg",
    backgroundImage: "/ambient/dawn-boat.jpg",
    backgroundPosition: "center center",
    view: {
      distance: 4.95,
      side: -1.1,
      height: 1.58,
      lookHeight: 1.36,
      lookSide: -0.28,
      fov: 31
    }
  },
  {
    id: "interactive",
    code: "08 / SISTEMA",
    label: "Sistema",
    kicker: "Escalabilidade editorial",
    headline: "Uma base pronta para crescer como portfólio, ferramenta de descoberta e porta de entrada comercial",
    blurb:
      "Com o menu atual, eu já provo um sistema navegável. A partir dele, o site pode evoluir para documento, intake, apresentação contextual e filtro de contato mais inteligente.",
    details:
      "Meu próximo passo não é adicionar ornamento. É transformar esta base em mecanismo mais forte de apresentação, triagem, proposta e aprofundamento, preservando assinatura visual e clareza de leitura.",
    bullets: [
      "Espaço para IA contextual",
      "Navegação por foco como eixo do sistema",
      "Transição entre portfólio, intake e ferramenta"
    ],
    contentTitle: "Onde este site pode crescer",
    contentBody:
      "Com o menu atual, eu já provo comportamento: hover realoca a câmera, isola a face visível e prepara o salto para uma navegação mais profunda. O próximo passo natural é fazer o mesmo sistema operar como documento útil, interface de descoberta e filtro de contato mais forte.",
    contentNotes: [
      "Expansão sem perder assinatura",
      "Navegação guiada por foco e prioridade",
      "Camadas futuras entrando sobre base viva"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / produto",
        title: "O que pode entrar sem trair a estrutura",
        body:
          "Eu posso adicionar novas seções, cenas, trilhas de aprofundamento, sons, modos de leitura e mais automação de contato. O importante é tudo continuar parecendo parte do mesmo organismo, e não um acoplado improvisado.",
        list: [
          "Intake guiado melhor do que formulário seco",
          "Apresentação que vira ferramenta de conversa",
          "Camadas contextuais por tipo de visitante"
        ]
      },
      {
        kicker: "Camada 2 / critério",
        title: "O que mantem a expansao no lugar certo",
        body:
          "Meu critério aqui é não trocar estrutura por barulho. Toda camada nova precisa aumentar utilidade, legibilidade ou força de assinatura. Se só chama atenção, mas não melhora a leitura, entra pesada demais.",
        list: [
          "Crescer com função clara",
          "Sustentar navegação compreensível",
          "Tratar estilo como parte do sistema, não maquiagem"
        ]
      }
    ],
    image: "/assets/foto-06.jpg",
    backgroundImage: "/assets/foto-06.jpg",
    backgroundPosition: "center 52%",
    view: {
      distance: 4.6,
      side: 0.35,
      height: 2.55,
      lookHeight: 1.8,
      lookSide: 0.1,
      fov: 26
    }
  },
  {
    id: "contact",
    code: "09 / FECHAMENTO",
    label: "Fechamento",
    kicker: "Assinatura profissional",
    headline: "Ambição com fundamento para construir interfaces, sistemas e portas de entrada com critério",
    blurb:
      "Eu fecho este portfólio amarrando o que me move: fundamento técnico, leitura de produto e ambição de entregar algo útil, bonito e economicamente relevante.",
    details:
      "Eu opero como construtor solo em design, UX, engenharia, requisitos e software autoral. O que me move é transformar essa combinação em trabalho sério, com assinatura, consistência e responsabilidade.",
    bullets: [
      "Fundamento como apoio, não como teto",
      "Design, UX, engenharia e negócio no mesmo corpo",
      "Ambição de excelência com leitura prática de mercado"
    ],
    contentTitle: "O que eu procuro sustentar em cada trabalho",
    contentBody:
      "Minha filosofia de trabalho nasce de uma vontade simples de dizer e difícil de sustentar: fazer melhor e responder a isso com entrega real. Nunca vi fundamento como limite; vejo como base para empurrar mais longe a qualidade do que construo.",
    contentNotes: [
      "Ambição com base técnica",
      "Entrega com responsabilidade e assinatura",
      "Mercado acessível, útil e interessante"
    ],
    deepDives: [
      {
        kicker: "Camada 1 / compromisso",
        title: "O que essa filosofia exige no dia a dia",
        body:
          "Essa filosofia me exige critério, insistência, desconforto com solução meia boca e disposição para lapidar. Também me exige dizer não quando algo ainda não tem base suficiente, mesmo que isso pareça menos sedutor no curto prazo.",
        list: [
          "Não empacotar vazio como se fosse proposta",
          "Não fingir clareza quando o projeto ainda está nebuloso",
          "Não abrir mão de assinatura para caber em fórmula pronta"
        ]
      },
      {
        kicker: "Camada 2 / afinidade",
        title: "O tipo de trabalho que mais conversa com meu perfil",
        body:
          "Os trabalhos que mais combinam comigo costumam misturar leitura de problema, interface forte, estrutura semântica, critério de produto e vontade de construir algo memorável sem perder utilidade.",
        list: [
          "Portas de entrada editoriais ou experienciais",
          "Produtos que ainda precisam encontrar sua forma certa",
          "Projetos em que critério visual e estrutural precisam andar juntos"
        ]
      }
    ],
    image: "/assets/foto-04.jpg",
    backgroundImage: "/ambient/night-sentinel.jpg",
    backgroundPosition: "center center",
    view: {
      distance: 4.8,
      side: 0,
      height: 1.38,
      lookHeight: 1.18,
      lookSide: 0,
      fov: 29
    }
  }
];
